#48 track health on component CR
cloudogu/k8s-component-operator pull request #49
Opened 2024-01-15 13:13 UTC by jelemux

Resolves #48

2024-01-15 13:20 UTC, cesmarvin commented on pkg/health/applicationFinder.go
> +	daemonSetList, err := af.appsClient.DaemonSets(namespace).List(ctx, metav1.ListOptions{LabelSelector: componentLabelSelector})
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>af.appsClient.DaemonSets undefined (type appsV1Client has no field or method DaemonSets)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/health/componentRepo.go
> +	component, err := cr.client.Get(ctx, name, metav1.GetOptions{})
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>cr.client.Get undefined (type componentClient has no field or method Get)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/health/componentRepo.go
> +		_, err = cr.client.UpdateStatus(ctx, component, metav1.UpdateOptions{})
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>cr.client.UpdateStatus undefined (type componentClient has no field or method UpdateStatus)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/health/deploymentController.go
> +		AppsV1().Deployments(request.Namespace).
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>dr.clientSet.AppsV1 undefined (type ecosystemClientSet has no field or method AppsV1)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/health/manager.go
> +		applicationFinder: &defaultApplicationFinder{appsClient: clientSet.AppsV1()},
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>clientSet.AppsV1 undefined (type ecosystemClientSet has no field or method AppsV1)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/health/manager.go
> +		componentRepo:     &defaultComponentRepo{client: clientSet.ComponentV1Alpha1().Components(namespace)},
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>clientSet.ComponentV1Alpha1 undefined (type ecosystemClientSet has no field or method ComponentV1Alpha1)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/health/statefulSetController.go
> +		AppsV1().StatefulSets(request.Namespace).
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>ssr.clientSet.AppsV1 undefined (type ecosystemClientSet has no field or method AppsV1)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/labels/postrenderer.go
> +	c.documentSplitter.WithReader(renderedManifests)
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>c.documentSplitter.WithReader undefined (type documentSplitter has no field or method WithReader)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/labels/postrenderer.go
> +	for c.documentSplitter.Next() {
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>c.documentSplitter.Next undefined (type documentSplitter has no field or method Next)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/labels/postrenderer.go
> +		obj, _, err := c.unstructuredSerializer.Decode(c.documentSplitter.Bytes(), nil, nil)
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>c.unstructuredSerializer.Decode undefined (type unstructuredSerializer has no field or method Decode)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/labels/postrenderer.go
> +		unstructuredMap, err := c.unstructuredConverter.ToUnstructured(obj)
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>c.unstructuredConverter.ToUnstructured undefined (type unstructuredConverter has no field or method ToUnstructured)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/labels/postrenderer.go
> +		yamlBytes, err := c.serializer.Marshal(k8sObject)
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>c.serializer.Marshal undefined (type genericYamlSerializer has no field or method Marshal)

2024-01-15 13:20 UTC, cesmarvin commented on pkg/labels/postrenderer.go
> +	if err = c.documentSplitter.Err(); err != nil {
🚫 **[checkstyle]** <typecheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>c.documentSplitter.Err undefined (type documentSplitter has no field or method Err)

2024-01-16 12:21 UTC, jelemux commented on pkg/health/applicationFinder.go
> +	deploymentList, err := af.appsClient.Deployments(namespace).List(ctx, metav1.ListOptions{LabelSelector: componentLabelSelector})
WTF, these are all methods that are very much defined

2024-01-17 09:46 UTC, jelemux commented on pkg/health/daemonSetController.go
> +package health
Gonna ignore this as we'd have to use Generics to resolve it.

2024-01-17 09:46 UTC, jelemux commented on pkg/health/deploymentController.go
> +package health
Gonna ignore this as we'd have to use Generics to resolve it.

2024-01-17 09:46 UTC, jelemux commented on pkg/health/statefulSetController.go
> +package health
Gonna ignore this as we'd have to use Generics to resolve it.

2024-01-17 14:07 UTC, alexander-dammeier requested changes
Just a little question to the testdata but everything else LGTM :)

2024-01-17 14:30 UTC, jelemux commented on pkg/labels/testdata/longhorn.yaml
> +
It's what the output of `helm template` for longhorn looks like. So yeah, it's definitely not bad data for testing :)

2024-01-18 15:57 UTC, alexander-dammeier commented on pkg/controllers/interfaces.go
> +}
good to know that our components are in an alpha phase^^

2024-01-19 16:15 UTC, cesmarvin commented on pkg/health/changeEventFilter.go
> +		newObj := event.ObjectNew.(*appsv1.Deployment)
🚫 **[checkstyle]** <forcetypeassert> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>type assertion must be checked

2024-01-19 16:15 UTC, cesmarvin commented on pkg/health/changeEventFilter.go
> +		newObj := event.ObjectNew.(*appsv1.StatefulSet)
🚫 **[checkstyle]** <forcetypeassert> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>type assertion must be checked

2024-01-19 16:15 UTC, cesmarvin commented on pkg/health/changeEventFilter.go
> +		newObj := event.ObjectNew.(*appsv1.DaemonSet)
🚫 **[checkstyle]** <forcetypeassert> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>type assertion must be checked

2024-01-19 16:15 UTC, cesmarvin commented on pkg/health/daemonSetController.go
> +package health
🚫 **[checkstyle]** <dupl> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>1-51 lines are duplicate of `pkg/health/deploymentController.go:1-51`

2024-01-19 16:15 UTC, cesmarvin commented on pkg/health/deploymentController.go
> +package health
🚫 **[checkstyle]** <dupl> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>1-51 lines are duplicate of `pkg/health/statefulSetController.go:1-51`

2024-01-19 16:15 UTC, cesmarvin commented on pkg/health/statefulSetController.go
> +package health
🚫 **[checkstyle]** <dupl> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>1-51 lines are duplicate of `pkg/health/daemonSetController.go:1-51`

2024-01-26 10:54 UTC, alexander-dammeier commented
lgtm

2024-01-26 10:55 UTC, merged